name: Linter

on: push

jobs:
  lint:
    name: Run rust-clippy analyzer
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy

      - name: Run rust-clippy
        run:
          cargo clippy --all-features
